name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        DOCKER_USER: julianusiv
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --file Dockerfile --tag julianusiv/lathbot:$(date +%s)
      
    - name: Push
      run: docker push julianusiv/lathbot
      
